### ISSUE TITLE
Digits recognition 

### ISSUE THREAD

**Issue by BlackCode101** [pavitrakumar78/Python-Custom-Digit-Recognition#3]
Hi, I am trying to detect and recognize digits (10,15,20,30...etc) written on the top of Fuse/Switch objects. the text color is white and the font is like in digital format.
i have tried many techniques by googling it and none worked for me. 
i also tried openCV and pytesseract.image_to_string but the results is totally a disaster.
i will really appreciate if you could please help me.
its really urgent and i need it for my final year project.

**Comment by pavitrakumar78** [comment]
The image used in this (Python-Custom-Digit-Recognition) is clean and easy to segment and recognize. Barely any image processing techniques were required. But if your image has more background noise, lighting effects, camera quality problems, you will need lots of preprocessing to detect it properly (check (here) [https://www.pyimagesearch.com/2017/02/13/recognizing-digits-with-opencv-and-python/]. The other approach is to use a more complex prediction model like a CNN and train on large amounts of data (check (here)[https://github.com/pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN]).

**Comment by BlackCode101** [comment]
Thank you so much for the reply. Can i share my image with you i think it is clear enough to be detected. I am extracting each fuse and then try to read the text but its not working.
I will really appreciate if you could please take a look to the image and if you have any relevant code please share with me.
Thanks,
Adnan.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pavitrakumar78** [comment]
Sure.

**Comment by pavitrakumar78** [comment]
Can't see the image.

**Comment by BlackCode101** [comment]
please confirm once you receive the image because i am keep on sending it
and i get a failure email.

**Comment by BlackCode101** [comment]
https://drive.google.com/drive/folders/1J2Mg8Nb5n1pGnkiM-oVf6QRJADzyOnzM?usp=sharing
please check this link.

**Comment by pavitrakumar78** [comment]
So, it looks like some of the numbers are inverted/reversed? That makes the problem a bit harder. But since the organization of the numbers are in a fixed and organized way, you can first work on that. Try to first manually cut the digits alone and send that through a pipeline (I hope you are not trying to do image recognition on the entire image...). Your first goal would be to make sure only the digit is visible clearly - try something like erosion and dilation ([here](https://docs.opencv.org/2.4/doc/tutorials/imgproc/erosion_dilatation/erosion_dilatation.html)) after you take care of filtering the background. Then, try the tesseract call on the processed image - I figure you'd get a better result with that itself.  
Try testing a processed image (sections of digits only, NOT the whole image) on this page: http://tesseract.projectnaptha.com/  
Good luck!

**Comment by BlackCode101** [comment]
No of course i am not doing it on the whole image. I have extracted small images and even extracted the center of the extracted image that will only contain numbers. And ya there are some numbers in reverse but we can ignore those for now. But the problem is i even converted it to grayscale and black and white but the result didn’t improve at all. I will try your suggestions also but in the meanwhile you got a chance to test a few images it will be a great help.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by BlackCode101** [comment]
Hi, I tried that one also but the text detection is still not improving. i am sharing my code with you, if you could please take a look:

import pytesseract
from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"
img = cv2.imread('images/Extracted/sub3.jpg',1)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# (threshi, img_bw) = cv2.threshold(img_gray, 150, 255, cv2.THRESH_BINARY)
# cv2.imshow('sad',img_bw)
img = img_gray

# kernel = np.ones((5,5),np.uint8)
# kernel =  cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
# kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))


#Erosion...
erosion = cv2.erode(img,kernel,iterations = 1)
plt.figure(figsize=(25, 25))
plt.subplot(331)
plt.imshow(img)
plt.title('Erosion')
plt.imshow(erosion)
print('Erosion...',pytesseract.image_to_string(erosion, config='--psm 8'))

#Dilation...
plt.subplot(332)
plt.imshow(img)
plt.title('Dilation')
dilation = cv2.dilate(img,kernel,iterations = 1)
plt.imshow(dilation)
print('Dilation...',pytesseract.image_to_string(dilation, config='--psm 8'))

#Opening...
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
plt.subplot(333)
plt.imshow(opening)
plt.title('Opening')
print('opening...',pytesseract.image_to_string(opening, config='--psm 8'))

#closing...
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
plt.subplot(334)
plt.imshow(closing)
plt.title('Closing')
print('closing...',pytesseract.image_to_string(closing, config='--psm 8'))

#Morphological Gradient..
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)
plt.subplot(335)
plt.imshow(closing)
plt.title('Morpholog Gradient')
print('Morphological...',pytesseract.image_to_string(gradient, config='--psm 8'))

#Top Hat..
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
plt.subplot(336)
plt.imshow(tophat)
plt.title('Top Hat')
print('Top Hat...',pytesseract.image_to_string(tophat, config='--psm 8'))

#Black Hat
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)
plt.subplot(337)
plt.imshow(blackhat)
plt.title('Black Hat')
print('Black Hat...',pytesseract.image_to_string(blackhat, config='--psm 8'))
plt.show()

**Comment by BlackCode101** [comment]
i have uploaded extracted images to google drive that i was trying:
https://drive.google.com/drive/folders/1J2Mg8Nb5n1pGnkiM-oVf6QRJADzyOnzM?usp=sharing

**Comment by pavitrakumar78** [comment]
Try reducing the image size that you are passing into tesseract. I'm sure there are some parameters you can tweak for each of the preprocessing steps you have described above - try tweaking those parameters. Also, you don't need all the preprocessing steps and the ordering is also important. I'd suggest you read search around StackOverflow for what the ordering of preprocessing steps should be and how you should go about experimenting with them.
